### ISSUE TITLE
'Unrecognized function or variable 'NB_REEFS'' in line 68

### ISSUE THREAD

**Issue by vinaykrishna64** [ymbozec/REEFMOD.6.4_GBR_HINDCAST#1]
if OPTIONS.doing_size_frequency == 1   
%% here
    nb_juv = zeros(NB_SIMULATIONS, NB_REEFS, NB_TIME_STEPS+1, 6, 4) ; %% <----- NB_REEFS, NB_TIME_STEPS are not defined
%%
    nb_adol = zeros(NB_SIMULATIONS,META.nb_reefs,META.nb_time_steps+1,META.nb_coral_types, 13,'single') ;
    nb_adult = zeros(NB_SIMULATIONS,META.nb_reefs,META.nb_time_steps+1,META.nb_coral_types, 9,'single') ; 
end

![image](https://github.com/user-attachments/assets/d4972602-eb01-4eec-81fa-13367f95dd31)

**Comment by ymbozec** [comment]
Thanks - it should be fixed now.
